name: Release

on:
  push:
    tags:
    - "v**"

jobs:

  release-github:
    name: Create Github Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true

  release-pypi:
    name: Release pypi package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install build
      run: pip install build
    - name: Build dists
      run: python -m build
    - name: Release to PyPI
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
